#+TILE: Linux Distros - Annotations

* Sumario
  :PROPERTIES:
  :TOC:      :include all :depth 2 :ignore this
  :END:
:CONTENTS:
- [[#progresso][Progresso]]
- [[#podman][Podman]]
  - [[#docs][docs]]
  - [[#commands][commands]]
  - [[#tricks][tricks]]
  - [[#fixes][fixes]]
- [[#docker][Docker]]
  - [[#fortschritt][Fortschritt]]
  - [[#dockerfile][Dockerfile]]
  - [[#traits][Traits]]
  - [[#commands][Commands]]
:END:
* Debian
** Apt commands
   | comando               | ... |
   |-----------------------+-----|
   | apt list --upgradable |     |
   | apt upgrade --dry-run |     |

*** debstrap
    - mmdebstrap --variant=minbase --include=init,python3 buster /tmp/chroot-python3 http://apt-proxy-ng:3142/debian
    chroot /tmp/chroot-python3 apt install --no-install-recommends xfce4  ===> 228 MB of additional disk space will be used.

*** update-alternatives
    $ update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1
** apt/preference
   #+begin_src conf
   Package: *
   Pin: release a=unstable
   Pin-Priority: 700

   Package: *
   Pin: release a=testing
   Pin-Priority: 500

   Package: *
   Pin: release a=stable
   Pin-Priority: 400

   Package: *
   Pin: release a=experimental
   Pin-Priority: -10

   #+end_src

** source.list.
   #+begin_src conf
   # [Unstable]
   deb http://ftp.br.debian.org/debian/ unstable contrib non-free main
   deb-src http://ftp.br.debian.org/debian/ unstable contrib non-free main

   # Testing
   deb http://ftp.br.debian.org/debian testing main contrib non-free
   deb-src http://ftp.br.debian.org/debian testing main contrib non-free

   # Stable
   deb http://ftp.br.debian.org/debian stable main contrib non-free
   deb-src http://ftp.br.debian.org/debian stable main contrib non-free

   # Security updates
   deb http://security.debian.org/ stable/updates main contrib non-free
   deb http://security.debian.org/ testing/updates main contrib non-free
   deb-src http://security.debian.org/ stable/updates main contrib non-free
   deb-src http://security.debian.org/ testing/updates main contrib non-free

   #+end_src
** Warning
   Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).

* NixOS
** progress
   | manual  | @                                   |
   |---------+-------------------------------------|
   | nix     | Chapter 14. A Simple Nix Expression |
   | nixpkgs |                                     |

** nix-shell
*** usage
    nix-shell -p pack1 pack2 --run 'make install PREFIX=/home/elxbarbosa/.local'

*** builds deps
**** rbenv
***** rbenv faster
      gcc
***** rbenv ruby
**** st
     freetype glibc pkg-config fontconfig gtk3-x11
* Ubuntu
* Fedora
* Gentoo
** Emerge errors
*** Not enough ram
    when you see "Killed (program cc1plus)" that means some external process killed cc1plus, it didnt die of its own error.  95% of the time, that's oom-killer. it could in theory be grsec, or even
    just some joker running "killall cc1plus" from another terminal, etc.

* Misc
  Get Distro Release: cat /etc/issue
