#!/usr/bin/env sh

# set -e

# * UBUNTU

e-ubuntu-packages()
{
    essentials=(ssh make build-essential git p7zip p7zip-full zip unzip zile neovim tmux curl wget bash emacs gcc)

    ruby=(python2 autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev)

    programming=(shellcheck zenity bash-completion m4 libtool libtool-bin default-jdk clang clangd lldb cmake)

    virtualization=(wine wine32 winetricks qemu qemu-system-x86 qemu-system-gui qemu-utils qemu-efi qemu-kvm virt-manager ovmf virt-manager) # libvirt-clients libvirt-daemon-system libvirt-dev libvirt0

    toolings=(htop zsh screen gdb ripgrep lshw at usbutils lsof time entr tree git xsel xclip exuberant-ctags fontconfig libfreetype6 subversion bc gdebi strace ltrace cpio lhasa lzop atool wmctrl poppler-utils brz mercurial sysstat jq dialog ncdu nnn fzf fzy rsync bat rclone xonsh pv vrms info stow parted texinfo autoconf automake gnutls-bin bash-doc gcc-doc gdb-doc gdbserver wget2 parallel nftables libiw-dev)

    fonts=(fonts-firacode fonts-dejavu ttf-ancient-fonts fonts-nanum)

    de=(firefox syncthing libreoffice calibre inkscape kdenlive deluge obs-studio vlc mpv steam inxi fish imagemagick pandoc screenfetch lm-sensors aspell gimp numix-icon-theme numix-gtk-theme)

    media=(ffmpeg vorbis-tools gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly)

    echo "Instalando pacotes."

    local command='sudo apt install -y'
    e_foreach "$command" "${essentials[@]}"
    e_foreach "$command" "${ruby[@]}"
    e_foreach "$command" "${fonts[@]}"; sudo fc-cache -fv
    e_foreach "$command" "${programming[@]}"
    e_foreach "$command" "${virtualization[@]}"
    e_foreach "$command" "${toolings[@]}"
    e_foreach "$command" "${de[@]}"
    e_foreach "$command" "${media[@]}"
}

e-ubuntu-upgrade()
{
    echo "-- Updating System"

    sudo apt -y update && sudo apt -y upgrade
    sudo apt -y autoremove
}

e-ubuntu-services()
{
    echo ""
}

e-ubuntu()
{
    e-ubuntu-upgrade
    e-ubuntu-packages
    #e-ubuntu-services
}
