#+TILE: Life Annotations

* Sumario
:PROPERTIES:
:TOC:      :include all :depth 2 :ignore this
:END:
:CONTENTS:
- [[#progress][Progress]]
  - [[#books-videos][Books, Videos]]
- [[#movies][Movies]]
  - [[#favorites][Favorites]]
- [[#tv-shows][TV Shows]]
  - [[#favorites][Favorites]]
- [[#books][Books]]
  - [[#favs][Favs]]
- [[#manga][Manga]]
  - [[#favorites][Favorites]]
- [[#games][Games]]
  - [[#steam][Steam]]
  - [[#fallout-1][Fallout 1]]
  - [[#wineproton][Wine/Proton]]
  - [[#alien-isolation][alien isolation]]
- [[#music][Music]]
  - [[#classic-composers][Classic Composers]]
  - [[#american][American]]
  - [[#japan][Japan]]
  - [[#bass][Bass]]
  - [[#cuba][Cuba]]
  - [[#christian][Christian]]
  - [[#djent][Djent]]
  - [[#death-metal][Death Metal]]
  - [[#progressive-metal][Progressive Metal]]
  - [[#rock][Rock]]
  - [[#mpb][MPB]]
  - [[#violao][Violao]]
  - [[#classic-guitar][Classic Guitar]]
- [[#gifts][Gifts]]
  - [[#nephew][Nephew]]
- [[#paintings][Paintings]]
- [[#donations][Donations]]
- [[#résumé][Résumé]]
- [[#delivery][Delivery]]
:END:
* Progress
** Books, Videos
| Books                  | Capts                      | @                               |
|------------------------+----------------------------+---------------------------------|
| Attack of Titan(manga) | Chapter 93                 |                                 |
| Last Wish              | The Voice of Reason 2      |                                 |
| The War of the Worlds  |                            |                                 |
| Study in Scarlet       | 2 The Science of Deduction | SHERLOCK HOLMES  -  his limits. |
| Plato: Five Dialogues  |                            |                                 |
* Movies
** Favorites
- 12 Angry Men
- 7 Samurai
- Casablanca
- Lawrence of Arabia
- Silence of Lambs
- Jurassic Park
- Lawman (Burt Lancaster)
- Alien
- The Maltese Falcon
- The Searchers
- Hearts in Atlantis
- Rashomon
- Stalker (Andrei Tarkovsky)
- La dolce Vita
- Judgement in Nuremberg
- To Kill A Mockingbird
- Anatomy of a Murder
- Inherit the Wind
- Witness for the Prosecution (1
- Spartacus
- Moby Dick (Gregory Pack)
- Planet of Apes
- Se7en
- Amistad
- The Shawshank Redemption
- The Third Man
- Let the Right One In
- 20,000 Leagues Under the Sea (Kirk Douglas)
- Rio Bravo
- High Noon
- True Git (John Wayne)
- For a Few Dollars More
- Escape from Alcatraz
- Shane
- The Wild Bunch
- No Country for Old Men
- Search Results
- Above the Law
- Shutter (Banjong Pisanthanakun)
- El espíritu de la colmena
- Rec
- El Bola
- The Seventh Seal
- Shin Godzilla
- GodZilla (Ishirō Honda)
- You Only Live Twice
- The Man with the Golden Gun
- Lake Mungo
- The Innocents (Jack Clayton)
- The Haunting 1963
- The Sixth Sense
- Signals
- Ghost
- Memories of Murder (Bong Joon-ho)
- The Last Man on Earth (Vincent Price)
- Independency Day
- The Fifth Element
* TV Shows
** Favorites
- Star Trek - The Next Generation
- Sherlock Holmes (Jeremy Brett)
- Chespirito
- Master's Sun
- Great Teacher Onizuka
- Full Metal Alchemist
- walking dead (season1 and 2)
- 1 Litre of Tears
- Trick
- Gokusen
- Kekkon Dekinai Otoko
- Dragon Zakura
- Grave of the Fireflies
- Spirited Away
- Chobits
- Bucky
- Dragon Ball Z
* Books
** Favs
- Dr Jekyll and Hide
- The Lost World

* Manga
** Favorites
- Lone Wolf and Cub
- One Punch Man
- Elfen Lied
- Love Hina
* Games
http://steamcommunity.com/id/elxbarbosa
** Steam
   cd ~/.steam/bin32
   LD_LIBRARY_PATH=. ldd vgui2_s.so

   look for missing libraries and install those

   then

   https://askubuntu.com/questions/1226371/steam-error-with-vgui2-s-so-unsure-how-to-repair
** Fallout 1
   FALLOUT COMBAT: Treat combat like a turn-based tactical game. Because it is.

   AP MANAGEMENT: Learn how to manage your AP because that's the cornerstone all
   future victory will build upon. Combat in the earlier Fallout games is far
   less forgiving than the later versions.

   AGILITY USEFULNESS: Agility sets both your AP pool, and your Sequence in
   combat. They are important.

   INVENTORY ACCESS: If you do not have something equipped in one of your two
   quick slots, you will need to access your inventory to use it. Accessing your
   inventory in combat costs AP. Thankfully, once you're in your inventory
   interface, you can do whatever you need without incurring any additional cost
   (provided you don't exit the inventory by mistake). There is a perk that you
   can take that lowers this AP cost. IT IS A VERY GOOD PERK AND YOU SHOULD TAKE
   IT. So, for example, you can equip a stimpak in one of your quick slots; in
   combat you can spend 2 AP to use it, get some health back and then it's spent
   -OR- you can spend 4 AP, open your inventory, and use as many stimpaks as you
   want and then get back into the fight.

   SHOOT OUTSIDE THE SCREEN TO RELOAD: You do not need to access your inventory
   to reload a weapon. If you right click on your equipped weapon, it will
   change the mode it's in. Swing vs Thrust, normal shot vs called shot, etc.
   With a firearm, one of the options you will cycle through is Reload.
   Reloading costs 2 AP, no click-and-dragging required.

   AP PERKS: Certain perks and traits will reduce the AP cost of certain
   actions, or give you additional AP to spend. Shit's dope, look into it.

   RUN FOR YOUR LIFE: Do not be afraid to run away. If you get caught in a fight
   you can't manage, just haul anus to the edge of the encounter map. There'll
   be some brown (or green, depending on where you are) exit grid texture on the
   ground - make it to there and you're home free.

   ALLIES ARE IMPORTANT: BRING FRIENDS. Every ally you have on your team means
   less hurt coming your way and more hurt you can put toward your enemies. Do
   be aware however that your NPC buddies may not be super cautious about having
   a clear lane of fire before shooting at baddies. If you have not been shot in
   the back by Ian at least once, then you are not really playing Fallout.

   SHANK BITCHES: Keep a close combat option handy. Knives never run out of
   ammo. Don't be afraid to stick and move - even if you have enough AP to stab
   a dude twice, instead try stabbing him once and then using the rest of your
   AP to fall back a few spaces. When his turn comes up, he'll have to spend
   some of his AP closing the distance, and may not have enough left to attack
   you.

   COME AT ME, BRO: Sometimes it's a good idea to let your enemy be the one to
   engage first. Especially if you have a good Sequence, your enemy will start
   combat (getting the first turn automatically), then you'll get your turn.
   THEN normal sequence order kicks in - and if you're fast that means you go
   first. The net result being: your enemy goes first, spends his first round
   closing the distance and then you get to take two rounds back to back. That
   shit can end a fight before it really begins.

   MEDICAL CARE: You can heal yourself with your First Aid and Doctor skills
   independent of having to use a stimpak. As using medical skills to treat
   injury takes time, it's not a great option in combat but is handy for
   downtime healing. Also each successful use of those skills will give you exp.
   Get up on that.

   READING IS FUNDAMENTAL: Cover-to-cover the manual. It has some good info in
   there and is worth the read. Fallout 1 is still part of that era where
   important shit went into the book rather than being tutorialized in the game
   itself.

   YOUR SKILL POINTS AND YOU: Not all skills are created equal. Frankly there
   are some skills that you shouldn't bother putting points into early in the
   game, or at all. Don't bother putting points into Big Guns or Energy Weapons
   early on - you aren't going to find a laser or a rocket launcher for a long
   damn time. Don't really put points into Gambling or Throwing at all, ever.
   They're tits on a fish. Useless. By comparison, skills like Small Guns, Melee
   Weapons or Unarmed (but probably not both), Speech, and Doctor are amazing.

   IT GOES TO 200: Skills in scale way differently in Fallout 1. For the first,
   they go up to 200. For the Second, that percentage sign all skills are
   measured by? That means how often you will succeed under IDEAL circumstances.
   For ranged combat, it's worse. Your Base To Hit is = (Skill-30) +
   ((PE - 2) * 16) - (HEX * 4) - (AC of Target) [- 10% at night if HEX >= 5].
   So, yeah. While a 75 may be a good Small guns skill in FO3, here, it could
   leave you with only a 47% chance to hit a Khan in leather 5 hexes away.
** Wine/Proton
*** Gothic 2
    WINEPREFIX=...steam/steamapps/compatdata/39510/pfx/ winetricks directmusic

    # Libraries tab -> existing overrides -> 'dsound' -> remove
    WINEPREFIX=...steam/steam/steamapps/compatdata/39510/pfx/ winecfg

    editor ...steam/steam/steamapps/common/Gothic II/system/Gothic.ini

*** Gothic 1
    WINEPREFIX=...steam/steam/steamapps/compatdata/65540/pfx/ winetricks directmusic

    # Libraries tab -> existing overrides -> 'dsound' -> remove
    WINEPREFIX=...steam/steam/steamapps/compatdata/65540/pfx/ winecfg

    editor ...steam/steam/steamapps/common/Gothic/system/Gothic.ini

    # Video BlackScreen CutScenes: graphics -> emulate a virtual desktop
    WINEPREFIX=...steam/steam/steamapps/compatdata/65540/pfx/ winecfg

*** Gothic Common

    Enable more screen resolutions:
    [INTERNAL] -> extendedMenu=1

    Fix Cutscenes BlackScreen:
    [GAME] -> scaleVideos=1

    Game Settings -> audio -> "Miles Fast" Provider

** alien isolation
   0340
* Music
** Classic Composers
- Berlioz
- Mahler
- Felix Mendelssohn
- Joseph Haydn
- Johann Sebastian Bach
- Wagner
- Camille Saint Saëns
- Vivaldi
- Tchaikovsky
- Rimsky-Korsakov
- Rachmaninoff
- Maurice Ravel
- Beethoven
- Dvořák
- Leoš Janáček
- Béla Bartók
- Edward Elgar
- Gabriel Fauré
- Arnold Schoenberg
** American
- Ink Spot


** Japan
- a-ha
- hy
- Tatsuro Yamashita
- ROUND TABLE featuring Nino
- k - only human

** Bass
- Marcus MIller

** Cuba
- Nat King Cole
- Perez Prado
- Compay Segundo
- Ibrahim Ferrer

** Christian
- DC talk
** Djent
- Acadence
- Animals as leaders
- Plini
- Vitalism
-
** Death Metal
- meshuggah
** Progressive Metal
- stratovarius
** Rock
- Deepeche Mode
** MPB
- Ze
** Violao
- Baden Powell
- Garoto
- Marco Pereira

** Classic Guitar
- John Williams
- Julian Bream
- Yepes
* Gifts
** Nephew
- Nintendo Switch
- College Car
* Paintings
- Candido Portinari
- J. M. W. Turner
* Donations
https://apoia.se/cozinhasolidaria
* Résumé
#+OPTIONS: toc:nil author:nil date:nil num:nil

*Euber Alexandre De Sousa Barbosa*

Brasília, DF - (61) 981103178

easbarbosa@tutanota.me
https://git.sr.ht/~easbarbosa

@easbarbosa

*SOBRE*
-----
  Sou usuário de Distribuições Linux por mais de 10 anos com foco em
  servidores com Kernel customizado, familiaridade de ferramentas
  cli como gerenciadores de empacotamento, make, cmake, ninja, rake,
  assim como grep, find, ps, ssh, windows managers e automação de
  tarefas com shell scripts.


*EDUCAÇÃO*
-----
  - Direito - IESB (Trancado)
  - Ciência da Computação, UCB (Cursando)


*SKILLS*
-----
  - Linguagens: Ruby e Emacs Lisp.
  - Debian/Fedora: administração, ferramentas e configurações.
  - Shell Script: GNU Bash, Fish Shell e POSIX.
  - Git: rebase, squash, merge.
  - Containers: podman, dockerfile, criação e gerência de imagens.
  - Unit Test: Minitest, RSpec, ERT.
  - Front-End: HTML,CSS Grid/Flexbox.
  - Editores: GNU Emacs, NeoVIM, Nano.


*MAIS*
-----
  - Inglês: Intermediário em conversação, Avancado em Leitura/Escrita/Ouvir.
  - Soft Skills em Secretário de Advocacia e Radio Taxi.

* Delivery
981103178
tn: 76c3da5a9b44f28fd8356ac7c886159af05e28426a64397197cd60999e33e782
