# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "amdgpu" ];
  boot.extraModulePackages = [ ];

hardware.opengl.extraPackages = with pkgs; [
   rocm-opencl-icd
   rocm-opencl-runtime
];

hardware.opengl.driSupport = true;
# For 32 bit applications
hardware.opengl.driSupport32Bit = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/47663699-b4fc-4382-9807-9f3b31faabca";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/23f2bafd-4ddb-484e-9823-9eba625a69de";
      fsType = "ext2";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e55c1a40-66d1-4dd6-9ff4-23c7f8a32193";
      fsType = "ext4";
    };

  fileSystems."/fun" =
    { device = "/dev/disk/by-uuid/ecdc24f5-5722-4a8d-9f2f-582c2ed84502";
      fsType = "ext4";
    };

  fileSystems."/dados" =
    { device = "/dev/disk/by-uuid/7bf3d173-72d6-4a78-9614-6e553de770da";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/D0F5-7E8F";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/999d716b-b246-40e0-90c3-50095ccd2361"; }
    ];

}
