#!/usr/bin/env bash

# Description: auto-start list of software toolings
# Deps: pgrep, command, bash4

# * Guards

[ "$DESKTOP_SESSION" == "plasma" ] && exit
[ "$DESKTOP_SESSION" == "gnome" ] && exit

# * Lists

tools=(/usr/bin/udiskie /usr/bin/mpd /usr/bin/blueman-applet /usr/bin/dunst)

apps=(/usr/bin/emacs "$HOME"/.local/bin/st /usr/bin/firefox
  /usr/bin/atril)

# * Helpers

not_found() {
  [[ ! -x $(command -v "$1") ]]
}

is_running() {
  [[ $(pgrep -f "$1") ]]
}

run() {
  "$1" &
}

autostart() {
  local apps=("$@")

  for app in "${apps[@]}"; do
    not_found "$app" && continue
    is_running "$app" && continue
    run "$app"
  done
}

wallpaper() {
  feh --bg-max --randomize ~/Pictures/wallpapers/* &
}

# * Run

wallpaper
autostart "${tools[@]}"
autostart "${apps[@]}"
