#!/usr/bin/env bash

[ "$DESKTOP_SESSION" == "plasmawayland" ] && kwallet-query -l kdewallet >/dev/null

if [ "$DESKTOP_SESSION" == "gnome" ]; then
    eval "$(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)"
    export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK
fi

KEYS_FOUND=$(find "$HOME/.ssh/" -type f -name '*.pub')

for KEY in $KEYS_FOUND; do
    ssh-add -q "$KEY" </dev/null
done
