#!/usr/bin/env bash

e-apps-docker(){
    user(){
	sudo groupadd docker
	sudo usermod -aG docker $USER
	newgrp docker
    }

    services(){
	sudo systemctl enable docker
    }


    user
    services
}

e-apps-binaries()
{
    bin="$HOME/bin"

    mkdir -pv "$bin"
    cd "$bin"

    local binaries=("https://dystroy.org/broot/download/x86_64-linux/broot"
		    "https://raw.githubusercontent.com/dylanaraps/pfetch/master/pfetch"
		    "https://raw.githubusercontent.com/nojhan/liquidprompt/master/liquidprompt")

    for binary in "${binaries[@]}"; do
	[[ ! -e "$bin/$binary" ]] && wget -c "$binary"
    done
}

e-apps-ssh()
{
    # Note: generate ssh key anew with: $ ssh-keygen -p

    [ -e "$HOME/.ssh/id_rsa.pub" ] && exit 0 # ssh key exist!

    echo " -- Generating a new SSH key"

    ssh-keygen  -t rsa -b 4096 -C "${USER}@outlook.com"

    echo " -- Press Enter"
    eval "$(ssh-agent -s)"
    ssh-add "$HOME/.ssh/id_rsa"

    echo "DONE"
}

e-apps-iso()
{
    sudo dd bs=4M if="$1" of="$2" status=progress oflag=sync
}
