#!/usr/bin/env sh

# set -e

e-build-emacs() {
    local BUILDS="$HOME/Builds"
    local EMACS_DIR="$BUILDS/emacs"
    local PREFIX="$HOME/.local"
    local TAG=emacs-27.1

    check-deps(){
	[[ ! -x $(command -v git) ]] && exit
    }

    repo-get()
    {
	[[ -d $EMACS_DIR ]] && return

	git clone "https://git.savannah.gnu.org/git/emacs" "$BUILDS/emacs"
    }

    repo-update()
    {
	[[ -d "$EMACS_DIR/.git" ]] && git pull
    }

    repo-checkout()
    {
	git checkout ${TAG}
    }

    install()
    {
	cd "$EMACS_DIR" || return

	make distclean

	sh autogen.sh

	sh configure --prefix="$PREFIX" --with-modules --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xft --with-xpm --with-x --with-dbus --with-imagemagick --with-mailutils --with-gnutls --with-x-toolkit=gtk3

	make -j2

	make install
    }

    # * RUN

    echo "Emacs - Installing local build"

    check-deps

    repo-get
    repo-update
    repo-checkout

    install
}
