#!/usr/bin/env sh

# set -e

# * Description: Add foreign packagers bin directories to $PATH
# * SOFTWARE $PATH


e_path_gem()
{
    local gem_bin="$HOME/.gem/ruby/2.7.0/bin"

    export PATH="$gem_bin"${PATH:+:}$PATH
}

e_path_asdf()
{
    source "$HOME"/.asdf/completions/asdf.bash
    source "$HOME"/.asdf/asdf.sh

    local asdf_shims_dir="$HOME"/.asdf/shims

    export PATH="$asdf_shims_dir"${PATH:+:}$PATH
}

e_path_cask()
{
    local caskdir="$HOME/.cask/bin"
    export PATH="$caskdir"${PATH:+:}$PATH
}

# * RUN

e_path_asdf
e_path_gem
e_path_cask
