#!/usr/bin/env bash

e-binaries()
{
    bin="$HOME/bin"

    mkdir -pv "$bin"
    cd "$bin"

    local binaries=("https://dystroy.org/broot/download/x86_64-linux/broot"
		    "https://raw.githubusercontent.com/dylanaraps/pfetch/master/pfetch"
		    "https://raw.githubusercontent.com/nojhan/liquidprompt/master/liquidprompt")

    for binary in "${binaries[@]}"; do
	[[ ! -e "$bin/$binary" ]] && wget -c "$binary"
    done
}

e-ssh()
{
    # Note: generate ssh key anew with: $ ssh-keygen -p

    [ -e "$HOME/.ssh/id_rsa.pub" ] && exit 0 # ssh key exist!

    echo " -- Generating a new SSH key"

    ssh-keygen  -t rsa -b 4096 -C "${USER}@outlook.com"

    echo " -- Press Enter"
    eval "$(ssh-agent -s)"
    ssh-add "$HOME/.ssh/id_rsa"

    echo "DONE"
}

e-iso()
{
    sudo dd bs=4M if="$1" of="$2" status=progress oflag=sync
}

e-dired()
{
    emacs -q -nw \
      --eval "(dired default-directory)" \
      --eval "(defun kill-window-or-emacs () (interactive) (if (one-window-p) (kill-emacs) (delete-window)))" \
      --eval "(setq dired-dwim-target t delete-by-moving-to-trash t )" \
      --eval "(dired-hide-details-mode)" \
      --eval "(define-key dired-mode-map (kbd \"q\") #'kill-window-or-emacs)"
}
