#!/usr/bin/env bash

# * Description: Add foreign packagers bin directories to $PATH
# * SOFTWARE

e_gem_path()
{
    local gem_bin="$HOME/.gem/ruby/2.7.0/bin"

    export PATH="$gem_bin"${PATH:+:}$PATH
}

e_asdf_path()
{
    source "$HOME"/.asdf/completions/asdf.bash
    source "$HOME"/.asdf/asdf.sh

    local asdf_shims_dir="$HOME"/.asdf/shims

    export PATH="$asdf_shims_dir"${PATH:+:}$PATH
}

e_rbenv_path()
{
    local rbenv_dir="$HOME/.rbenv"

    local rbenv_shims="$rbenv_dir/shims"
    local rbenv_bin="$rbenv_dir/bin"

    export PATH="$rbenv_bin"${PATH:+:}$PATH
    export PATH="$rbenv_shims"${PATH:+:}$PATH
}

e_nvm_path()
{
    local nvm_dir="$HOME/.config/nvm"

    [ -s "$nvm_dir/nvm.sh" ] && source "$nvm_dir/nvm.sh"  # Loads NVM
    [ -s "$nvm_dir/bash_completion" ] && source "$nvm_dir/bash_completion"  # Loads NVM Bash Completion

    local nvm_bin="$(nvm_version_dir)/$(nvm_version)/bin"
    export PATH="$nvm_bin"${PATH:+:}$PATH
}

e_luarocks_path()
{
    export PATH="$HOME/.luarocks/bin"${PATH:+:}$PATH
}

e_cask_path()
{
    local caskdir="$HOME/.cask/bin"
    export PATH="$caskdir"${PATH:+:}$PATH
}

# * RUN

e_gem_path
e_asdf_path
e_cask_path
# e_rbenv_path
# e_nvm_path
# e_luarocke_path
