#!/usr/bin/env sh

# set -e

e-apps-podman()
{
    echo 'PODMAN :)'
}

e-apps-gitconfig()
{
    git config --global init.defaultBranch main

    git config --global user.name "$USER"
    git config --global user.email "$USER@gmail.com"

    git config --global core.editor "emacs -nw"
    git config --global core.autocrlf input
    git config --global core.excludesfile  "$USER/.gitignore_global"

    git config --global color.ui true

    git config --global credential.helper cache --timeout=1600

    git config --global pull.ff only
}

e-apps-docker(){
    user(){
	sudo groupadd docker
	sudo usermod -aG docker $USER
	newgrp docker
    }

    services(){
	sudo systemctl enable docker
    }


    user
    services
}

e-apps-binaries()
{
    bin="$HOME/bin"

    mkdir -pv "$bin"
    cd "$bin"

    local binaries=("https://dystroy.org/broot/download/x86_64-linux/broot"
		    "https://raw.githubusercontent.com/dylanaraps/pfetch/master/pfetch"
		    "https://raw.githubusercontent.com/nojhan/liquidprompt/master/liquidprompt")

    for binary in "${binaries[@]}"; do
	[[ ! -e "$bin/$binary" ]] && wget -c "$binary"
    done
}

e-apps-ssh()
{
    # Note: generate ssh key anew with: $ ssh-keygen -p -f /path/to/ssh_key

    [ -e "$HOME/.ssh/id_rsa.pub" ] && exit 0 # ssh key exist!

    echo " -- Generating a new SSH key"

    ssh-keygen -t ed25519 -C "$USER@gmail.com"

    # ssh-add -K ~/.ssh/id_ed25519

    # verify w/ ssh -T git@gitlab.com

    eval "$(ssh-agent -s)"

    echo "DONE"
}

e-apps-gpg()
{
    gpg --full-generate-key
    # "TIP: RSA Default -> 4096 bits"
}

e-apps-iso()
{
    sudo dd bs=4M if="$1" of="$2" status=progress oflag=sync
}

e-apps-run()
{
    e-apps-ssh
    e-apps-gpg
    e-apps-binaries
    e-apps-podman
}
