#!/usr/bin/env sh

# set -e

e-packs-asdf()
{
    echo 'Installing asdf'

    # https://asdf-vm.com/#/core-manage-asdf
    # https://asdf-vm.com/#/core-manage-plugins
    # https://asdf-vm.com/#/core-commands
    # https://asdf-vm.com/#/plugins-all

    asdf-install()
    {
	local asdf_dir="$HOME/.asdf"

	if [[ ! -d $asdf_dir ]]; then
	    git clone https://github.com/asdf-vm/asdf.git "$asdf_dir"

	    cd "$asdf_dir" && git checkout "$(git describe --abbrev=0 --tags)"
	fi
    }

    asdf-activate()
    {
	source "$HOME"/.asdf/completions/asdf.bash
	source "$HOME"/.asdf/asdf.sh

	local asdf_shims_dir="$HOME"/.asdf/shims
	[[ -d $asdf_shims_dir ]] && return

	export PATH="$asdf_shims_dir"${PATH:+:}$PATH
    }

    asdf-install
    asdf-activate

    asdf update
}

e-packs-asdf-golang()
{
    echo 'Installing golang binaries'

    # https://github.com/kennyp/asdf-golang

    asdf plugin-add golang https://github.com/kennyp/asdf-golang.git

    asdf install golang latest

    asdf global golang "$(asdf latest golang)"
}

e-packs-asdf-python()
{
    echo 'Installing python binaries'

    # https://github.com/danhper/asdf-python

    asdf plugin-add python

    asdf install python latest

    asdf global python "$(asdf latest python)"
}

e-packs-asdf-ruby()
{
    echo 'Installing ruby binaries'

    # https://github.com/asdf-vm/asdf-ruby

    asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git

    asdf install ruby latest

    asdf global ruby "$(asdf latest ruby)"
}

e-packs-golang()
{
    echo 'Installing golang packages'

    GO111MODULE=on

    local packages=("golang.org/x/tools/gopls@latest" "sigs.k8s.io/kind")

    for pack in "${packages[@]}"
    do
	go get -u "${pack}"
    done

}

e-packs-ruby()
{
    echo 'Installing gem packages'

    local packages=(bundler solargraph rubocop pry reek clipboard rspec)

    for pack in "${packages[@]}"
    do
	[[ $(command -v nixos-version) ]] && nix-shell -p gcc zlib --run '"gem install ${pack}"'

	gem install "${pack}" --user-install
	gem update  "${pack}"
    done
}

e-packs-python()
{
    echo 'Installing pip packages'

    local packages=(pip ansible wheel setuptools blackyoutube-dl python-language-server
		    pyls-black pyls-isort pyls-mypy jedi ipython pylama
		    pyflakes flake8-import-order pydocstyle flake8 mccabe yapf
		    pylint rope pytest pep8-naming mutagen)

    for pack in "${packages[@]}"
    do
	python3 -m pip install --upgrade --user "${pack}"
    done
}

e-packs-all()
{
    echo 'Installing language package manager packages'

    e-packs-golang
    e-packs-ruby
    e-packs-python
}

e-packs-asdf-all()
{
    echo 'Installing asdf backends'

    e-packs-asdf
    e-packs-asdf-ruby
    e-packs-asdf-python
}

e-packs-run()
{
    e-packs-asdf-all
    e-packs-all
}
