#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x bspwmbar > /dev/null || bspwmbar &

bspc monitor -d I II III IV V 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs desktop='^1'
bspc rule -a Atril desktop='^2'
bspc rule -a Alacritty desktop='^3'
bspc rule -a Chromium desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Gimp desktop='^8' state=floating follow=on