[[config]]
name = "rschmukler-doom.d"
url = "https://github.com/rschmukler/doom.d"

[[config]]
name = "tecosaur-emacs-config"
url = "https://github.com/tecosaur/emacs-config"

[[config]]
name = "abo-abo-oremacs"
branch = "github"
url = "https://github.com/abo-abo/oremacs"

[[config]]
name = "jwiegley-dot-emacs"
url = "https://github.com/jwiegley/dot-emacs"

[[config]]
name = "doom-emacs"
url = "https://github.com/hlissner/doom-emacs"

[[config]]
name = "unpackaged.el"
url = "https://github.com/alphapapa/unpackaged.el"

[[config]]
name = "elfeed"
url = "https://github.com/skeeto/elfeed"

[[config]]
name = "lsp-mode"
url = "https://github.com/emacs-lsp/lsp-mode"

[[config]]
name = "use-package"
url = "https://github.com/jwiegley/use-package"

[[config]]
name = "emacs"
url = "git://git.sv.gnu.org/emacs"
