[[config]]
name = "tpm"
url = "https://github.com/tmux-plugins/tpm"

[[config]]
name = "sdras-awesome-actions"
branch = "main"
url = "https://github.com/sdras/awesome-actions"

[[config]]
name = "github-gitignore"
branch = "main"
url = "https://github.com/github/gitignore"

[[config]]
name = "makefiletutorial"
branch = "gh-pages"
url = "https://github.com/theicfire/makefiletutorial"

[[config]]
name = "aschmelyun-cleaver"
branch = "main"
url = "https://github.com/aschmelyun/cleaver"

[[config]]
name = "juancrg90-clean-code-notes"
url = "https://github.com/JuanCrg90/Clean-Code-Notes"
