[[config]]
name = "pygit2"
url = "https://github.com/libgit2/pygit2"

[[config]]
name = "httpie"
url = "https://github.com/httpie/httpie"

[[config]]
name = "poetry"
url = "https://github.com/python-poetry/poetry"

[[config]]
name = "django"
branch = "main"
url = "https://github.com/django/django"

[[config]]
name = "fastapi"
url = "https://github.com/tiangolo/fastapi"

[[config]]
name = "flask"
branch = "main"
url = "https://github.com/pallets/flask"

[[config]]
name = "requests"
branch = "main"
url = "https://github.com/psf/requests"

[[config]]
name = "black"
branch = "main"
url = "https://github.com/psf/black"

[[config]]
name = "cpython"
branch = "main"
url = "https://github.com/python/cpython"
