task = "Containers Images"
deps = [ "podman" ]
command = "podman pull"

[jobs]
languages = [
  "docker.io/library/python:3-slim",
  "docker.io/library/composer:lts",
  "docker.io/library/php:8"
]
database = [
  "docker.io/library/postgres:15",
  "docker.io/library/mariadb:10.7"
]
servers = [
  "docker.io/library/httpd:2",
  "docker.io/library/nginx:stable"
]
distributions = [
  "docker.io/library/debian:stable-slim",
  "docker.io/library/debian:unstable-slim",
  "docker.io/library/ubuntu:lunar",
  "docker.io/library/busybox:glibc"
]

