topic = "Containers Images"
deps = [ "podman" ]
install = "podman pull"

[jobs]
langs = [
  "docker.io/library/eclipse-temurin:17-jdk",
  "docker.io/library/eclipse-temurin:21-jdk",
  "docker.io/library/eclipse-temurin:8-jdk",
  "docker.io/library/eclipse-temurin:8-jre"

]
database = [
  "docker.io/library/mongo:7",
  "docker.io/library/postgres:16"
]
distributions = [
  "docker.io/library/debian:unstable",
  "docker.io/library/alpine:latest"
]

