task = "Containers Images"
deps = [ "podman" ]
command = "podman pull"

[jobs]
languages = [
  "docker.io/library/python:3.11",
  "docker.io/library/composer:lts"
]
database = [
  "docker.io/library/postgres:15",
  "docker.io/library/mariadb:10.7"
]
distributions = [
  "docker.io/library/debian:unstable-slim"
]

