task = "Containers Images"
deps = [ "podman" ]
command = "podman pull"

[jobs]
langs = [
  "docker.io/library/node:20",
  "docker.io/library/golang:1.21"
]
database = [
  "docker.io/library/mysql:8.3",
  "docker.io/library/postgres:16"
]
distributions = [
  "docker.io/library/debian:unstable",
  "docker.io/library/alpine:latest"
]

