task = "Containers Images"
deps = [ "podman" ]
command = "podman pull"

[jobs]
langs = [
  "docker.io/library/rust:1.76",
  "docker.io/library/golang:1.21",
  "docker.io/library/node:20"
]
database = [
  "docker.io/library/mongo:7",
  "docker.io/library/postgres:16"
]
distributions = [
  "docker.io/library/debian:unstable",
  "docker.io/library/alpine:latest"
]

