task = "Containers Images"
deps = [ "podman" ]
command = "podman pull"

[jobs]
langs = [
  "mcr.microsoft.com/dotnet/sdk:7.0",
  "mcr.microsoft.com/dotnet/runtime:7.0",
  "mcr.microsoft.com/dotnet/aspnet:7.0",
  "docker.io/library/mono:6-slim",
  "docker.io/library/eclipse-temurin:8-jdk",
  "docker.io/library/eclipse-temurin:8-jre",
  "docker.io/library/eclipse-temurin:17-jdk",
  "docker.io/library/eclipse-temurin:21-jdk"
  "docker.io/library/node:18",
  "docker.io/library/python:3.12"
]
database = [
  "mcr.microsoft.com/mssql/server:latest",
  "docker.io/library/postgres:16",
  "docker.io/library/mariadb:11"
]
distributions = [
  "docker.io/library/debian:unstable-slim"
]

