task = "Containers Images"
deps = [ "podman" ]
command = "podman pull"

[jobs]
langs = [
  "docker.io/library/php:8",
  "docker.io/library/composer:lts",
  "docker.io/library/eclipse-temurin:8-jdk",
  "docker.io/library/eclipse-temurin:8-jre",
  "docker.io/library/eclipse-temurin:17-jdk",
  "docker.io/library/eclipse-temurin:21-jdk"
  "docker.io/library/node:18",
  "docker.io/library/python:3.12"
]
database = [
  "mcr.microsoft.com/mssql/server:latest",
  "docker.io/library/postgres:16",
  "docker.io/library/mariadb:11"
]
distributions = [
  "docker.io/library/debian:unstable-slim"
]

