topic = "Containers Images"
deps = [ "podman" ]
install = "podman pull"

[jobs]
langs = [
 "docker.io/library/python:3.11"
]
database = [
  "docker.io/library/mysql:8",
  "docker.io/library/mongo:7",
  "docker.io/library/postgres:16"
]
distributions = [
  "docker.io/library/debian:unstable",
  "docker.io/library/alpine:latest"
]

