task = "Containers Images"
deps = [ "podman" ]
command = "podman pull"

[jobs]
langs = [
  "mcr.microsoft.com/dotnet/sdk:7.0",
  "mcr.microsoft.com/dotnet/runtime:7.0",
  "mcr.microsoft.com/dotnet/aspnet:7.0",
  "docker.io/library/mono:6-slim"
]
database = [
  "docker.io/library/postgres:16",
  "docker.io/library/mariadb:11"
]
distributions = [
  "docker.io/library/debian:unstable-slim"
]

