task = "Containers Images"
deps = [ "podman" ]
command = "podman pull"

[jobs]
langs = [
  "docker.io/library/php:8.2-fpm",
  "docker.io/library/composer:lts",
  "docker.io/library/node:18",
  "docker.io/library/python:3.12"
]
database = [
  "docker.io/library/postgres:16",
  "docker.io/library/mariadb:11"
]
distributions = [
  "docker.io/library/debian:unstable-slim"
]

