task = "Containers Images"
deps = [ "podman" ]
command = "podman pull"

[jobs]
langs = [
  "docker.io/library/node:20",
  "docker.io/library/python:3.12"
]
database = [
  "docker.io/library/mongo:7",
  "docker.io/library/postgres:16",
  "docker.io/library/mariadb:11"
]
distributions = [
  "docker.io/library/debian:unstable-slim"
]

