task = "Containers Images"
deps = [ "podman" ]
command = "podman pull"

[jobs]
langs = [
  "docker.io/library/golang:1"
]
database = [
  "docker.io/library/postgres:15",
  "docker.io/library/mariadb:11"
]
distributions = [
  "docker.io/library/debian:unstable-slim"
]

