task = "Containers Images"
deps = [ "podman" ]
command = "podman pull"

[jobs]
languages = [
  "docker.io/library/php:8",
  "docker.io/library/composer:lts",
  "docker.io/library/python:3.11"
]
database = [
  "docker.io/library/postgres:15",
  "docker.io/library/mariadb:11"
]
distributions = [
  "docker.io/library/debian:unstable-slim"
]

