task = "Containers Images"
deps = [ "podman" ]
command = "podman pull"

[jobs]
langs = [
    "docker.io/library/eclipse-temurin:8-jdk",
  "docker.io/library/eclipse-temurin:8-jre",
  "docker.io/library/eclipse-temurin:17-jdk",
  "docker.io/library/eclipse-temurin:21-jdk"
]
database = [
  "docker.io/library/postgres:16",
  "docker.io/library/mariadb:11"
]
distributions = [
  "docker.io/library/debian:unstable-slim"
]

