topic = "Containers Images"
deps = [ "podman" ]
install = "podman pull"

[jobs]
langs = [
  "docker.io/library/eclipse-temurin:21-jdk",
  "docker.io/library/node:20"
]
database = [
  "docker.io/library/postgres:16"
]
distributions = [
  "docker.io/library/debian:unstable",
  "docker.io/library/alpine:latest"
]

