topic = "Arch Linux - dev"
refresh = "sudo pacman -Syy"
upgrade = "pacman -Syu"
install = "sudo pacman -S --noconfirm"
post = [
     "sudo usermod -a -G libvirt $USER"
]
deps = [ "pacman" ]

[packages]
gnu = [
  "gcc"
]
editors = [ "vim", "neovim" ]
tools = [
  "scdoc",
  "git",
  "subversion",
  "mercurial",
  "editorconfig-core-c",
  "jq",
  "fd",
  "fzf",
  "tidy",
  "ripgrep",
  "shfmt",
  "taplo-cli",
  "inotify-tools",
]
design = [
  "krita"
]
langs = [
  "go"
  "guile"
  "npm",
  "nodejs",
  "python"
]
vm = [
  "qemu-base",
  "libvirt",
  "bridge-utils",
  "virt-install",
  "dnsmasq"
]
cc = [
  "meson",
  "clang",
  "cmake",
  "doxygen"
]
