topic = "Arch Linux - dev"
refresh = "sudo pacman -Syy"
upgrade = "pacman -Syu"
install = "sudo pacman -S --noconfirm"
deps = [ "pacman" ]

[packages]
gnu = [
  "gcc"
]
editors = [ "vim", "neovim" ]
tools = [
  "scdoc",
  "git",
  "subversion",
  "mercurial",
  "editorconfig-core-c",
  "jq",
  "fd",
  "tidy",
  "ripgrep",
  "shfmt",
  "taplo-cli"
]
images = [
  "krita"
]
langs = [
  "go",
  "npm",
  "nodejs",
  "python",
  "guile"
]
cc = [
  "meson",
  "clang",
  "cmake"
]
