topic = "Arch Linux - dev"
refresh = "sudo pacman -Syy"
upgrade = "pacman -Syu"
install = "sudo pacman -S --noconfirm"
deps = [ "pacman" ]

[packages]
editors = [ "vim", "neovim" ]
tools = [
  "scdoc",
  "git"  
  "jq",
  "subversion",
  "mercurial",
  "editorconfig-core",
  "direnv",
  "fd",
  "tidy",
  "ripgrep",
  "shfmt"
]
cc = [
  "meson",
  "clang"
]
images = [ "krita" ]
