topic = "Arch Linux"
refresh = "sudo pacman -Syy"
upgrade = "pacman -Syu"
install = "sudo pacman -S --noconfirm"
deps = [ "pacman" ]
post = [ 
    "systemctl --user enable pipewire.service",
    "systemctl --user start pipewire.service",
    "systemctl --user enable pipwire-pulse.service",
    "systemctl --user start pipwire-pulse.service"
]
[packages]
gnu = [
    "wget"
]
system = [
  "openssh",
  "unzip",
  "zip",
  "p7zip",
  "at",
  "usbutils",
  "lsof",
  "atool",
  "time",
  "entr",
  "tree",
  "bc",
  "curl",
  "strace",
  "ltrace",
  "cpio",
  "lhasa",
  "lzop",
  "rsync",
  "pv",
  "texinfo",
  "autoconf",
  "automake",
  "socat",
  "tmux",
  "bottom",
  "unrar"
]
arch = [ "base-devel" ]
shell = [ "bash-completion", "shellcheck" ]
fonts = [
  "ttf-hack",
  "ttf-dejavu",
  "ttf-jetbrains-mono",
  "adobe-source-han-sans-otc-fonts",
  "noto-fonts",
  "noto-fonts-emoji",
  "ttf-liberation",
  "ttf-droid",
  "adobe-source-sans-fonts"
]
laptop = [ 
    "acpi", 
    "lm-sensors", 
    "lshw", 
    "libinput-tools", 
    "acpid" 
]
wayland = [ 
    "sway",
    "swaylock",
    "swayidle",
    "foot",
    "wl-clipboard",
    "wayland-protocols",
    "bemenu",
    "grim",
    "slurp",
    "mako",
    "udiskie",
    "mpd",
    "mpc",
    "ncmpcpp"
]
cli = [
  "htop",
  "ffmpeg",
  "mpv",
  "elinks",
  "libnotify",
  "ranger",
  "aria2",
  "cmus"
]
user = [
  "chromium",
  "firefox",
  "libreoffice",
  "gimp",
  "xdg-utils",
  "imagemagick",
  "aspell",
  "aspell-pt",
  "aspell-en",
  "calibre",
  "pandoc",
  "obs-studio",
  "inkscape",
  "vlc",
  "thunderbird"
]
sound = [
  "pipewire",
  "pipewire-pulse",
  "lib32-pipewire",
  "pipewire-docs",
  "wireplumber",
  "pulseaudio-utils"
]
media = [
  "gstreamer",
  "gst-libav",
  "gst-plugins-bad",
  "gst-plugins-base",
  "gst-plugins-good",
  "gst-plugins-ugly"
]
amd = [
  "amd-ucode",
  "mesa",
  "lib32-mesa",
  "xf86-video-amdgpu",
  "vulkan-radeon",
  "lib32-vulkan-radeon"
]
