topic = "Arch Linux - Ops"
refresh = "sudo pacman -Syy"
upgrade = "pacman -Syu"
install = "sudo pacman -S --noconfirm"
deps = [ "pacman" ]

[packages]
servers = [ "nginx" ]
network = [
  "gnutls",
  "net-tools",
  "iproute2",
  "perl-net-telnet",
  "dnsutils",
  "iwd",
  "iw",
  "wireless_tools",
  "resolvconf",
  "gnu-netcat",
  "tcpdump",
  "httpie"
]
kubernetes = [ "kubectl", "kubelet", "kubeadm", "helm" ]
cloud = [ "awscli", "google-cloud-sdk" ]
misc = [ "gitlab-runner" ]
