manager = "Debian Development Tools"
command = "sudo apt-get install -y"
deps = ["apt"]

[packages]
langs = [
      "sbcl",
      "nodejs",
      "npm",
      "python3-pip",
      "python3-venv"
]
games = [
      "libsfml-dev"
]
database = [ "sqlite3" ]
tools = [
    "jq",
    "git-email",
    "subversion",
    "mercurial",
    "libpq-dev",
    "editorconfig",
    "fd-find",
    "ripgrep",
    "shfmt",
    "meson",
    "cmake",
    "grip",
    "tidy",
    "fzf",
    "distrobox",
    "neofetch"
]
editors = [
    "emacs",
    "vim",
    "neovim"
]
emacs-pdftools = [
  "autoconf",
  "automake",
  "gcc",
  "libpng-dev",
  "libpoppler-dev",
  "libpoppler-glib-dev",
  "libz-dev",
  "make",
  "pkg-config"
]
images = [ "krita" ]
