manager = "Debian Development Tools"
command = "sudo apt-get install -y"
deps = ["apt"]

[packages]
python = [ "python3-pip", "python3-venv" ]
php = [
    "php",
    "php-common",
    "php-cli",
    "php-curl",
    "php-mbstring",
    "php-dom"
]
ruby = [ "ruby-full" ]
tools = [
    "jq",
    "git-email",
    "subversion",
    "mercurial",
    "libpq-dev",
    "editorconfig",
    "direnv",
    "fd-find",
    "shfmt",
    "meson",
    "cmake",
    "grip",
    "tidy",
    "ripgrep",
    "fzf"
]
editors = [
    "vim",
]
emacs = [
  "autoconf",
  "automake",
  "gcc",
  "libpng-dev",
  "libpoppler-dev",
  "libpoppler-glib-dev",
  "libz-dev",
  "make",
  "pkg-config"
]
