topic = "Debian Development Tools"
install = "sudo apt-get install -y"
deps = ["apt"]

[packages]
langs = [
   "guile-3.0",
   "guile-3.0-dev",
   "python3-pip",
   "python3-venv",
   "perl",
   "perl-doc"
]
cpp = [
    "cmake",
    "glslang-tools",
]
c-tools = [
  "clang-18",
  "clangd-18",
  "clang-format-18",
  "meson",
  "muon-meson",
  "gdb",
  "gprof",
  "valgrind",
  "splint",
  "indent"
]
c-libs = [
    "libpq-dev",
    "libsfml-dev"
]
jdk = [
   "openjdk-21-jdk",
   "openjdk-21-jre"
],
database = [ "sqlite3" ]
tools = [
    "jq",
    "git-email",
    "subversion",
    "mercurial",
    "editorconfig",
    "shfmt",
    "grip",
    "tidy",
    "fzf",
    "distrobox",
]
editors = [
    "vim",
    "neovim"
]
emacs = [
    "emacs",
    "fd-find",
    "ripgrep",
]
emacs-pdftools = [
  "autoconf",
  "automake",
  "gcc",
  "libpng-dev",
  "libpoppler-dev",
  "libpoppler-glib-dev",
  "libz-dev",
  "make",
  "pkg-config"
]
serial = [
    "libxml2-utils"
]
images = [ "krita" ]
