topic = "Debian Development Tools"
install = "sudo apt-get install -y"
deps = ["apt"]

[packages]
tools = [
    "jq",
    "git-email",
    "subversion",
    "mercurial",
    "editorconfig",
    "shfmt",
    "grip",
    "tidy",
    "fzf",
    "distrobox",
    "protobuf-compiler",
    "inotify-tools"
]
editors = [
    "vim",
    "neovim",
    "micro"
]
emacs = [
    "emacs",
    "fd-find",
    "ripgrep"
]
emacs-pdftools = [
  "autoconf",
  "automake",
  "gcc",
  "libpng-dev",
  "libpoppler-dev",
  "libpoppler-glib-dev",
  "libz-dev",
  "make",
  "pkg-config"
]
images = [
  "krita",
  "blender"
]
langs = [
 "guile-3.0",
 "python3-pip",
 "python3-venv"
]
cc-tools = [
  "meson",
  "muon-meson",
  "gdb",
  "gprof",
  "valgrind",
  "splint",
  "indent",
  "cmake",
  "glslang-tools",
  "clang-18",
  "clangd-18",
  "clang-format-18",
  "clang-tidy-18"
]
gnu = [
   "gdb"
]
database = [ "sqlite3" ]
