topic = "Debianzao das massas"
install = "sudo apt-get install -y"
refresh = "sudo apt update"
upgrade = "sudo apt upgrade -y"
pre = "sudo dpkg --add-architecture i386"
deps = ["apt"]
post = [
    "sudo apt-file update",
    "sudo apt remove -y firefox-esr xdg-desktop-portal*",
    "sudo dpkg-reconfigure locales",
]

[packages]
gnu = [
    "bash",
    "gcc",
    "make",
    "info",
    "wget",
    "parallel",
    "gawk",
    "parted",
    "gimp"
]
debian = [
    "build-essential",
    "apt-file",
    "gdebi"
]
system = [
    "flatpak",
    "git",
    "ssh",
    "curl",
    "unzip",
    "tmux",
    "zip",
    "p7zip",
    "p7zip-full",
    "recutils",
    "at",
    "usbutils",
    "lsof",
    "atool",
    "time",
    "entr",
    "tree",
    "bc",
    "strace",
    "ltrace",
    "cpio",
    "lhasa",
    "lzop",
    "rsync",
    "pv",
    "texinfo",
    "autoconf",
    "automake",
    "socat",
    "aspell",
    "ispell"
]
laptop = [
    "acpi",
    "lm-sensors",
    "lshw",
    "libinput-tools",
    "acpid",
    "tlp",
    "vainfo",
    "i965-va-driver",
    "libvdpau-va-gl1",
    "libiw-dev",
    "acpi-call",
    "dialog",
    "sysstat",
    "hddtemp"
]
cli = [
    "htop",
    "w3m",
    "libnotify-bin",
    "aria2"
]
shell = [
    "bash-completion",
    "shellcheck"
]
wayland = [
  "xwayland",
  "wl-clipboard"
]
misc = [
    "cheese"
]
user = [
  "firefox",
  "thunderbird",
  "libreoffice",
  "xdg-utils",
  "imagemagick",
  "aspell",
  "aspell-pt-br",
  "calibre",
  "pandoc",
  "obs-studio"
]
sound = [
     "pulseaudio-utils",
     "pipewire",
     "pipewire-audio",
     "wireplumber",
     "pipewire-pulse",
     "pipewire-alsa",
     "pipewire-jack",
     "libspa-0.2-bluetooth"
]
media = [
    "ffmpeg",
    "mpv",
    "vorbis-tools",
    "gstreamer1.0-plugins-bad",
    "gstreamer1.0-plugins-base",
    "gstreamer1.0-plugins-good",
    "gstreamer1.0-plugins-ugly"
]
fonts = [
    "fonts-hack",
    "fonts-dejavu",
    "fonts-jetbrains-mono",
    "ttf-ancient-fonts",
    "fonts-nanum",
    "ttf-mscorefonts-installer",
    "cmigemo"
]
amd = [
    "amd64-microcode",
    "firmware-amd-graphics",
    "libgl1-mesa-dri",
    "libglx-mesa0",
    "mesa-utils",
    "libgl1-mesa-glx",
    "mesa-vulkan-drivers",
    "xserver-xorg-video-all",
    "libglx-mesa0:i386",
    "mesa-vulkan-drivers:i386",
    "libgl1-mesa-drivers:i386",
    "radeontop"
]
wm = [
  "brightnessctl",
  "udiskie",
  "cmus",
  "playerctl",
  "mako-notifier",
  "sway",
  "grimshot",
  "foot",
  "dmenu",
  "yambar"
]
