manager = "Debian Development Tools"
command = "sudo apt-get install -y"
deps = ["apt"]

[packages]
python = [ "python3-pip", "python3-venv" ]
java = [
     "openjdk-20-jdk",
     "openjdk-20-jre",
     "openjdk-20-doc",
     "openjdk-20-dbg",
     "clang-format"
]
tools = [
    "jq",
    "git-email",
    "subversion",
    "mercurial",
    "libpq-dev",
    "editorconfig",
    "direnv",
    "fd-find",
    "shfmt",
    "meson",
    "cmake",
    "grip",
    "tidy",
    "ripgrep",
    "fzf"
]
editors = [
    "vim",
]
emacs-deps = [
  "autoconf",
  "automake",
  "gcc",
  "libpng-dev",
  "libpoppler-dev",
  "libpoppler-glib-dev",
  "libz-dev",
  "make",
  "pkg-config"
]
