topic = "Debian Development Tools"
install = "sudo apt-get install -y"
deps = ["apt"]

[packages]
langs = [
   "python3-pip",
   "python3-venv",
   "guile-3.0",
   "guile-3.0-dev"
]
database = [ "sqlite3" ]
tools = [
    "jq",
    "git-email",
    "subversion",
    "mercurial",
    "editorconfig",
    "shfmt",
    "grip",
    "tidy",
    "fzf",
    "distrobox",
    "protobuf-compiler",
    "inotify-tools"
]
editors = [
    "vim",
    "neovim",
    "micro"
]
emacs = [
    "emacs",
    "fd-find",
    "ripgrep",
]
emacs-pdftools = [
  "autoconf",
  "automake",
  "gcc",
  "libpng-dev",
  "libpoppler-dev",
  "libpoppler-glib-dev",
  "libz-dev",
  "make",
  "pkg-config"
]
serial = [
    "libxml2-utils"
]
images = [ "krita" ]
cpp = [
  "cmake",
  "glslang-tools",
  "clang-18",
  "clangd-18",
  "clang-format-18",
]
cc-tools = [
  "meson",
  "muon-meson",
  "gdb",
  "gprof",
  "valgrind",
  "splint",
  "indent"
]
