manager = "Debian Development Tools"
command = "sudo apt-get install -y"
deps = ["apt"]

[packages]
default = [ "python3-pip" ]
java = [ "openjdk-17-jdk", "openjdk-17-jre", "clang-format" ]
tools = [
    "jq",
    "git-email",
    "subversion",
    "mercurial",
    "libpq-dev",
    "editorconfig",
    "direnv",
    "fd-find",
    "shfmt",
    "meson",
    "cmake",
    "grip",
    "tidy",
    "ripgrep",
    "fzf"
]
editors = [
    "vim",
]
emacs = [
  "autoconf",
  "automake",
  "gcc",
  "libpng-dev",
  "libpoppler-dev",
  "libpoppler-glib-dev",
  "libz-dev",
  "make",
  "pkg-config"
]
