manager = "Debian Development Tools"
command = "sudo apt-get install -y"
deps = ["apt"]

[packages]
cc = [
   "clangd",
   "clang-format"
]
langs = [
      "python3-pip",
      "python3-venv"
]
libs = [
    "libpq-dev",
    "libsfml-dev"
]
database = [ "sqlite3" ]
tools = [
    "jq",
    "meson",
    "muoun-meson",
    "git-email",
    "subversion",
    "mercurial",
    "editorconfig",
    "shfmt",
    "cmake",
    "grip",
    "tidy",
    "fzf",
    "distrobox",
]
editors = [

    "vim",
    "neovim"
]
emacs = [
    "emacs",
    "fd-find",
    "ripgrep",
]
emacs-pdftools = [
  "autoconf",
  "automake",
  "gcc",
  "libpng-dev",
  "libpoppler-dev",
  "libpoppler-glib-dev",
  "libz-dev",
  "make",
  "pkg-config"
]
images = [ "krita" ]
