topic = "Debian Development Tools"
install = "sudo apt-get install -y"
deps = ["apt"]

[packages]
tools = [
    "jq",
    "git-email",
    "subversion",
    "mercurial",
    "editorconfig",
    "shfmt",
    "grip",
    "tidy",
    "fzf",
    "distrobox",
    "protobuf-compiler",
    "inotify-tools"
]
libs = [
  "libssl-dev"
]
editors = [
    "vim",
    "neovim",
    "micro"
]
emacs = [
    "emacs",
    "fd-find",
    "ripgrep"
]
emacs-pdftools = [
  "autoconf",
  "automake",
  "gcc",
  "libpng-dev",
  "libpoppler-dev",
  "libpoppler-glib-dev",
  "libz-dev",
  "make",
  "pkg-config"
]
images = [
  "krita",
  "blender"
]
langs = [
 "python3-pip",
 "python3-venv"
]
gnu = [
 "guile-3.0",
 "gdb"
]
database = [ "sqlite3" ]
java = [
     "openjdk-21-jre",
     "openjdk-21-jdk",
     "clang-format"
]
