manager = "Debian Development Tools"
command = "sudo apt-get install -y"
deps = ["apt"]

[packages]
gnu = [
    "gdb",
]
c = [
   "meson",
   "muoun-meson"
]
cpp = [
  "clang-16",
  "clang-format-16",
  "clangd-16",
  "glslang-tools",
  "clangd-16",
  "clang-format-16"
  "cmake",
]
langs = [
    "python3-pip",
    "python3-venv"
]
libs = [
    "libpq-dev",
    "libsfml-dev"
]
database = [ "sqlite3" ]
tools = [
    "jq",
    "git-email",
    "subversion",
    "mercurial",
    "editorconfig",
    "shfmt",
    "grip",
    "tidy",
    "fzf",
    "distrobox",
]
editors = [

    "vim",
    "neovim"
]
emacs = [
    "emacs",
    "fd-find",
    "ripgrep",
]
emacs-pdftools = [
  "autoconf",
  "automake",
  "gcc",
  "libpng-dev",
  "libpoppler-dev",
  "libpoppler-glib-dev",
  "libz-dev",
  "make",
  "pkg-config"
]
images = [ "krita" ]
