topic = "Debian Development Tools"
install = "sudo apt-get install -y"
deps = ["apt"]

[packages]
langs = [
   "python3-pip",
   "python3-venv",
   "golang"
]
cc-tools = [
  "meson",
  "muon-meson",
  "gdb",
  "gprof",
  "valgrind",
  "splint",
  "indent",
  "cmake",
  "glslang-tools",
  "clang-18",
  "clangd-18",
  "clang-format-18",
  "clang-tidy-18"
]
c-libraries = [
    "libpq-dev",
    "libsfml-dev",
    "libtag1-dev",
    "libtagc0-dev"
    "libgit2-dev",
    "libinih-dev",
    "libjson-c-dev"
]
gnu = [
   "gdb",
]
gnome = [
  "gnome-devel",
  "glslc",
  "libdrm-dev"
]
database = [ "sqlite3" ]
tools = [
    "jq",
    "git-email",
    "subversion",
    "mercurial",
    "editorconfig",
    "shfmt",
    "grip",
    "tidy",
    "fzf",
    "distrobox",
    "protobuf-compiler",
    "inotify-tools"
]
editors = [
    "vim",
    "neovim",
    "micro"
]
emacs = [
    "emacs",
    "fd-find",
    "ripgrep"
]
emacs-pdftools = [
  "autoconf",
  "automake",
  "gcc",
  "libpng-dev",
  "libpoppler-dev",
  "libpoppler-glib-dev",
  "libz-dev",
  "make",
  "pkg-config"
]
serial = [
    "libxml2-utils"
]
images = [
  "krita",
  "blender"
]
