manager = "Debian Development Tools"
command = "sudo apt-get install -y"
deps = ["apt"]

[packages]
gnu = [
   "gdb",
]
c = [
   "valgrind",
   "meson",
   "muon-meson",
   "splint",
   "indent",
   "check",
   "libcunit1"
]
cpp = [
   "cmake",
   "clang-17",
   "clangd-17",
   "clang-format-17"
]
langs = [
   "golang",
   "guile-3.0",
   "chicken-bin",
   "python3-pip",
   "python3-venv"
]
libs = [
    "libpq-dev",
    "libsfml-dev"
]
gui = [
    "libgtk-4-dev",
    "libgtk-4-1",
	 "gtk-4-examples"
]
database = [ "sqlite3" ]
tools = [
    "jq",
    "git-email",
    "subversion",
    "mercurial",
    "editorconfig",
    "shfmt",
    "grip",
    "tidy",
    "fzf",
    "distrobox",
]
editors = [
    "vim",
    "neovim"
]
emacs = [
    "emacs",
    "fd-find",
    "ripgrep",
]
emacs-pdftools = [
  "autoconf",
  "automake",
  "gcc",
  "libpng-dev",
  "libpoppler-dev",
  "libpoppler-glib-dev",
  "libz-dev",
  "make",
  "pkg-config"
]
serial = [
    "libxml2-utils"
]
images = [ "krita" ]
