manager = "Fedora Dev Tools"
refresh = "sudo dnf update --assumeyes"
upgrade = "sudo dnf upgrade --assumeyes"
command = "sudo dnf install --assumeyes"
deps = [ "dnf" ]

[packages]
langs = [ "nodejs", "npm", "python3-pip" ]
java = [
     "java-17-openjdk",
     "java-17-openjdk-devel",
     "maven",
     "ant",
     "clang-tools-extra"
]
editors = [ "emacs", "vim", "neovim" ]
tools = [
  "jq",
  "subversion",
  "mercurial",
  "editorconfig",
  "direnv",
  "fd",
  "tidy",
  "ripgrep",
  "shfmt",
  "cmake",
  "make",
  "fd-find",
  "fzf"
]
emacs-pdftools = [
  "libpng-devel",
  "poppler-devel",
  "poppler-glib-devel",
  "zlib-devel",
  "pkgconf",
  "automake",
  "gcc",
  "autoconf"
]
images = [ "krita" ]
