topic = "Fedora Ops Tools"
refresh = "sudo dnf update --assumeyes"
upgrade = "sudo dnf upgrade --assumeyes"
install = "sudo dnf install --assumeyes"
deps = [ "dnf" ]

[packages]
langs = [ "ansible", "terraform" ]
