manager = "Fedora Foreign Tools"
refresh = "sudo dnf updaten--assumeyes"
upgrade = "sudo dnf upgrade --assumeyes"
command = "sudo dnf install --assumeyes"
deps = [ "dnf" ]
pre = [
    "sudo dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm",
    "sudo dnf install -y https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm",
    "sudo dnf config-manager -y --set-enabled google-chrome"
]
post = [ "sudo dnf group upgrade --assumeyes --with-optional Multimedia --allowerasing" ]

[packages]
apps = [
     "vlc", "steam", "google-chrome-stable"
]
media = [
      "gstreamer1-plugins-{bad-*,good-*,base}",
      "gstreamer1-plugin-openh264",
      "gstreamer1-libav --exclude=gstreamer1-plugins-bad-free-devel",
      "lame* --exclude=lame-devel"
]
