manager = "Fedora Dev Tools"
refresh = "sudo dnf update --assumeyes"
upgrade = "sudo dnf upgrade --assumeyes"
command = "sudo dnf install --assumeyes"
deps = [ "dnf" ]

[packages]
langs = [
      "guile30",
      "golang-bin",
      "python3-pip",
      "nodejs",
      "npm"
]
c-deps = [
       "cjson",
       "cjson-devel"
]
editors = [ "emacs", "vim", "neovim" ]
tools = [
  "jq",
  "subversion",
  "mercurial",
  "editorconfig",
  "fd",
  "tidy",
  "ripgrep",
  "shfmt",
  "cmake",
  "make",
  "fd-find",
  "fzf",
  "neofetch"
]
emacs-pdftools = [
  "libpng-devel",
  "poppler-devel",
  "poppler-glib-devel",
  "zlib-devel",
  "pkgconf",
  "automake",
  "gcc",
  "autoconf"
]
images = [ "krita" ]
