manager = "Fedora"
refresh = "sudo dnf update --assumeyes"
upgrade = "sudo dnf upgrade --assumeyes"
command = "sudo dnf install --assumeyes"
deps = [ "dnf" ]
pre = [ "sudo dnf install -y fedora-workstation-repositories"]

[packages]
system = [ "sepolicy", "dnf-plugins-core", "p7zip", "p7zip-plugins" ]
shell = [ "bash-completion", "ShellCheck" ]
fonts = [
  "hack-fonts",
  "dejavu-fonts",
  "noto-fonts",
  "jetbrains-mono-fonts",
  "liberation-fonts",
  "google-droid-fonts"
]
gnome = [
  "gnome-music",
  "gnome-tweaks",
  "gnome-extensions-app",
  "gnome-music",
  "transmission-gtk"
]
laptop = [ "acpi", "sensors", "lshw", "acpid" ]
wayland = [ "wl-clipboard" ]
cli = [
  "htop",
  "bottom",
  "ffmpeg",
  "mpv",
  "elinks",
  "libnotify",
  "ranger",
  "aria2",
  "btop",
  "lm_sensors"
]
user = [
  "chromium",
  "firefox",
  "libreoffice",
  "gimp",
  "thunderbird",
  "xdg-utils",
  "ImageMagick",
  "aspell",
  "aspell-pt_BR",
  "aspell-en",
  "calibre",
  "pandoc",
  "obs-studio",
  "inkscape",
  "exaile"
]
media = [
  "gstreamer1",
  "gstreamer1-libav",
  "gstremer-plugins-bad",
  "gstreamer1-plugins-base",
  "gstreamer1-plugins-good",
  "gstreamer1-plugins-ugly-free"
]

