manager = "Flatpak"
upgrade = "flatpak update -y"
command = "flatpak install flathub -y"
pre = [ "sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo" ]
post = [ 'flatpak uninstall --unused' ]
deps = [ "flatpak" ]

[packages]
apps = [
  "com.discordapp.Discord",
  "com.slack.Slack",
  "us.zoom.Zoom",
  "com.skype.Client",
  "com.google.Chrome"
]
