manager = "Flatpak"
upgrade = "flatpak update"
command = "flatpak install flathub -y"
deps = [ "flatpak" ]

[packages]
tools = [ "io.github.NhekoReborn.Nheko" ]
apps = [
  "com.discordapp.Discord",
  "com.slack.Slack",
  "us.zoom.Zoom",
  "com.skype.Client"
]
