manager = "Flatpak"
upgrade = "flatpak update -y"
command = "flatpak install flathub -y"
deps = [ "flatpak" ]

[packages]
apps = [
  "com.discordapp.Discord",
  "com.slack.Slack",
  "us.zoom.Zoom",
  "com.skype.Client",
  "com.google.Chrome",
  "org.telegram.desktop"
]
tools = [
  "com.getpostman.Postman",
  "io.github.NhekoReborn.Nheko",
  "io.podman_desktop.PodmanDesktop",
  "com.valvesoftware.Steam"
]
ides = [
  "org.eclipse.Java",
  "com.jetbrains.IntelliJ-IDEA-Community"
]
