manager = "GNU Guix Development Tools"
refresh = "guix pull"
upgrade = "guix package -u"
command = "guix install"
deps = [ "guix" ]

[packages]
langs = [ "guile", "guile-readline", "php" ]
editors = [ "zile", "emacs", "neovim" ]
misc = [ "nss-certs", "openssl", "font-dejavu" ]
apps = [ "haunt", "guile-hall", "akku" ]
libs = [ "guile-git", "guile-json" ]

