topic = "GNU Guix Main Tools"
refresh = "guix pull"
upgrade = "guix package -u"
install = "guix install"
deps = [ "guix" ]

[packages]
misc = [ "glibc-locales" ]
gnu = [  "ccal" ]
apps = [ "neofetch", "unrar-free", "grimshot", "yambar-wayland" ]
