topic = "GNU Guix Development Tools"
refresh = "guix pull"
upgrade = "guix package -u"
install = "guix install"
deps = [ "guix" ]

[packages]
langs = [ "guile", "guile-readline", "janet", "chez-scheme", "node", "smalltalk" ]
editors = [ "zile", "emacs-pgtk", "neovim" ]
ssl = [ "nss-certs", "openssl"  ]
misc = [ "font-dejavu" ]
apps = [ "haunt", "guile-hall", "akku" ]
libs = [ "guile-git", "guile-json" ]

