manager = "Nix Development Tools"
deps = [ "nix" ]
upgrade = "nix-env -u '*'"
command = "nix-env -iA"

[packages]
langs = [
  "nixpkgs.swift",
  "nixpkgs.swiftPackages.swiftpm",
  "nixpkgs.swift-format",
  "nixpkgs.swiftPackages.Foundation",
  "nixpkgs.swiftPackages.stdenv",
  "nixpkgs.swiftPackages.XCTest"
]
