topic = "Ubuntu - Ops tooling"
install = "sudo apt-get install -y"
refresh = "sudo apt update"
upgrade = "sudo apt upgrade -y"
deps = [ "apt" ]

[packages]
iac = [
    "ansible-core"
]
cloud = [
      "awscli"
]
network = [
        "httpie",
        "net-tools"
]
