topic = "Ubuntu Development Tools"
install = "sudo apt-get install -y"
deps = [ "apt" ]
post = "sudo apt -y autoremove"

[packages]
langs = [
    "guile-3.0",
    "python3-pip", 
    "python3-venv"
]
tools = [
  "jq",
  "git-email",
  "subversion",
  "mercurial",
  "editorconfig",
  "fd-find",
  "shfmt",
  "fzf",
  "tidy", 
  "ripgrep",
  "uuid"
]
editors = [ 
    "vim",
    "neovim",
]
gnu = [ 
 "emacs"
 "gcc",
 "make"
]   
emacs-pdftools = [
  "autoconf",
  "automake",
  "libpng-dev",
  "libpoppler-dev",
  "libpoppler-glib-dev",
  "libz-dev",
  "pkg-config"
]
cc = [
  "meson",
  "cmake"
]
cc-libs = []
