manager = "Ubuntu Development Tools"
command = "sudo apt-get install -y"
deps = [ "apt" ]
post = "sudo apt -y autoremove"

[packages]
python = [ "python3-pip", "python3-venv" ]
tools = [
  "jq",
  "git-email",
  "subversion",
  "mercurial",
  "editorconfig",
  "direnv",
  "fd-find",
  "shfmt",
  "meson"
]
editors = [ "vim", "tidy", "ripgrep" ]

