manager = "Ubuntu Development Tools"
command = "sudo apt-get install -y"
deps = [ "apt" ]
post = "sudo apt -y autoremove"

[packages]
langs = [ "nodejs", "npm" ]
php = [ "php", "php-cli", "php-curl", "php-mbstring", "php-dom"]
python = [ "python3-pip", "python3-venv" ]
tools = [
  "jq",
  "git-email",
  "subversion",
  "mercurial",
  "editorconfig",
  "direnv",
  "fd-find",
  "shfmt",
  "meson",
  "grip"
]
editors = [ "vim", "tidy", "ripgrep" ]

