manager = "Ubuntu - Foreign tooling"
command = "sudo apt-get install -y"
refresh = "sudo apt update"
upgrade = "sudo apt upgrade -y"
deps = [ "apt" ]

[packages]
iac = [
    "terraform"
]
orchestration = [
    "kubectl",
    "kubelet",
    "kubeadm"
]
