manager = "Ubuntu"
command = "sudo apt-get install -y"
refresh = "sudo apt update"
upgrade = "sudo apt upgrade -y"
pre = "sudo dpkg --add-architecture i386"
deps = [ "apt" ]

[packages]
amd = [
  "amd64-microcode",
  "firmware-amd-graphics",
  "libgl1-mesa-dri",
  "libglx-mesa0",
  "mesa-utils",
  "libgl1-mesa-glx",
  "mesa-vulkan-drivers",
  "xserver-xorg-video-all",
  "libglx-mesa0:i386",
  "mesa-vulkan-drivers:i386",
  "libgl1-mesa-drivers:i386",
  "radeontop"
]
cli = [
  "htop",
  "elinks",
  "libnotify-bin",
  "ranger",
  "aria2",
  "neofetch",
  "unrar",
  "bash-completion", 
  "shellcheck" 
]
ubuntu = [
  "build-essential",
  "aptitude",
  "apt-file",
  "gdebi",
  "reportbug"
]
fonts = [
  "fonts-hack",
  "fonts-dejavu",
  "fonts-jetbrains-mono",
  "ttf-ancient-fonts",
  "fonts-nanum",
  "ttf-mscorefonts-installer",
  "cmigemo"
]
gnu = [
  "bash",
  "gcc",
  "make",
  "info",
  "wget",
  "parallel",
  "gawk",
  "parted"
]
laptop = [
  "acpi",
  "lm-sensors",
  "lshw",
  "libinput-tools",
  "acpid",
  "tlp",
  "vainfo",
  "i965-va-driver",
  "libvdpau-va-gl1",
  "libiw-dev",
  "acpi-call",
  "dialog",
  "sysstat",
  "hddtemp",
  "btop"
]
gnome = [
  "gnome-shell-extensions",
  "gnome-music",
  "gnome-tweaks",
  "gnome-console"
]
wayland = [ "wl-clipboard" ]
wm = [
  "sway",
  "waybar",
  "mpd",
  "mpc",
  "ncmpcpp",
  "brightnessctl",
  "grimshot",
  "mako",
  "udiskie",
  "alacritty"
]
user = [
  "firefox",
  "libreoffice",
  "gimp",
  "xdg-utils",
  "imagemagick",
  "aspell",
  "aspell-pt-br",
  "calibre",
  "pandoc",
  "obs-studio",
  "inkscape",
  "transmission-gtk"
]
system = [
  "flatpak",
  "git",
  "ssh",
  "curl",
  "unzip",
  "tmux",
  "zip",
  "p7zip",
  "p7zip-full",
  "recutils",
  "at",
  "usbutils",
  "nscd",
  "lsof",
  "atool",
  "time",
  "entr",
  "tree",
  "bc",
  "strace",
  "ltrace",
  "cpio",
  "lhasa",
  "lzop",
  "rsync",
  "pv",
  "texinfo",
  "autoconf",
  "automake",
  "socat"
]

sound = [ "pulseaudio-utils" ]
media = [
  "ffmpeg",
  "mpv",
  "vorbis-tools",
  "gstreamer1.0-plugins-bad",
  "gstreamer1.0-plugins-base",
  "gstreamer1.0-plugins-good",
  "gstreamer1.0-plugins-ugly"
]
libs = [ "libtag1-dev", "libtagc0-dev" ]

