manager = "Ubuntu Development Tools"
command = "sudo apt-get install -y"
deps = [ "apt" ]
post = "sudo apt -y autoremove"

[packages]
containers = [ "podman" ]
langs = [
    "nodejs",
    "npm",
    "python3-pip", 
    "python3-venv",
    "lua5.4"
]
java = [
     "openjdk-17-jdk",
     "openjdk-17-jre",
     "maven",
     "ant",
     "clang-format"
]
emacs-pdftools = [
  "autoconf",
  "automake",
  "gcc",
  "libpng-dev",
  "libpoppler-dev",
  "libpoppler-glib-dev",
  "libz-dev",
  "make",
  "pkg-config"
]
tools = [
  "jq",
  "git-email",
  "subversion",
  "mercurial",
  "editorconfig",
  "fd-find",
  "shfmt",
  "meson",
  "cmake",
  "fzf",
  "tidy", 
  "ripgrep",
  "uuid"
]
editors = [ 
    "vim",
    "neovim",
    "emacs"
]

