manager = "Ubuntu Development Tools"
command = "sudo apt-get install -y"
deps = [ "apt" ]
post = "sudo apt -y autoremove"

[packages]
python = [ "python3-pip", "python3-venv" ]
java = [ "openjdk-17-jdk", "openjdk-17-jre" ]
emacs = [
  "autoconf",
  "automake",
  "gcc",
  "libpng-dev",
  "libpoppler-dev",
  "libpoppler-glib-dev",
  "libz-dev",
  "make",
  "pkg-config"
]
tools = [
  "jq",
  "git-email",
  "subversion",
  "mercurial",
  "editorconfig",
  "direnv",
  "fd-find",
  "shfmt",
  "meson",
  "cmake",
  "fzf"
]
editors = [ "vim", "tidy", "ripgrep" ]

