topic = "dotnet"
deps = [ "dotnet" ]
update = "dotnet tool update --global"
install = "dotnet tool install --global"

[packages]
langs = [ "csharp-ls", "Microsoft.dotnet-httprepl --version 6.0.0" ]
tools = [ "csharpier", "dotnet-outdated-tool", "csharprepl" ]
aspnet = [ "dotnet-aspnet-codegenerator", "dotnet-ef" ]
shell = [ "powershell" ]
fsharp = [ "paket", "fsautocomplete" ]
