topic = "dotnet"
deps = [ "dotnet" ]
update = "dotnet tool update --global"
install = "dotnet tool install --global"

[packages]
tools = [ "powershell", "csharp-ls", "csharpier", "dotnet-outdated-tool" ]
aspnet = [ "dotnet-aspnet-codegenerator", "dotnet-ef" ]
