lang = "dotnet"
deps = [ "dotnet" ]
command = "dotnet tool install --global"
command-update = "dotnet tool update --global"

[packages]
tools = [ "PowerShell", "csharp-ls" ]
aspnet = [ "dotnet-aspnet-codegenerator", "dotnet-ef" ]
