lang = "golang"
deps = [ "go" ]
command = "go install -v"

[packages]
lsp = [
  "github.com/hashicorp/terraform-ls@latest",
  "golang.org/x/tools/gopls@latest"
]
tools = [
  "-tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest",
  "github.com/cheat/cheat/cmd/cheat@latest",
  "github.com/fatih/gomodifytags@latest",
  "github.com/rogpeppe/godef@latest",
  "github.com/x-motemen/gore/cmd/gore@latest",
  "github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest",
  "github.com/ramya-rao-a/go-outline@latest",
  "github.com/go-delve/delve/cmd/dlv@latest",
  "github.com/cweill/gotests/...@latest",
  "github.com/ramya-rao-a/go-outline@latest",
  "github.com/mdempsky/gocode@latest",
  "github.com/githubnemo/CompileDaemon@latest",
  "golang.org/x/tools/cmd/guru@latest",
]
devel = [
  "github.com/erning/gorun@latest",











  "github.com/x-motemen/gore/cmd/gore@latest"
]
