topic = "golang"
deps = [ "go" ]
install = "go install -v"

[packages]
lsp = [
  "golang.org/x/tools/gopls@latest",
  "github.com/hashicorp/terraform-ls@latest"
]
tools = [
  "github.com/cheat/cheat/cmd/cheat@latest",
  "github.com/fatih/gomodifytags@latest",
  "github.com/rogpeppe/godef@latest",
  "github.com/x-motemen/gore/cmd/gore@latest",
  "github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest",
  "github.com/ramya-rao-a/go-outline@latest",
  "github.com/go-delve/delve/cmd/dlv@latest",
  "github.com/cweill/gotests/...@latest",
  "github.com/ramya-rao-a/go-outline@latest",
  "github.com/mdempsky/gocode@latest",
  "github.com/githubnemo/CompileDaemon@latest",
  "golang.org/x/tools/cmd/guru@latest",
  "github.com/jessfraz/dockfmt@latest",
  "github.com/jesseduffield/lazygit@latest"
]
devel = [
  "mvdan.cc/sh/v3/cmd/shfmt@latest",
  "github.com/erning/gorun@latest",
  "github.com/x-motemen/gore/cmd/gore@latest"
]
apps = [
  "github.com/xxxserxxx/gotop/v4/cmd/gotop@latest",
  "github.com/antonmedv/llama@latest",
  "github.com/BurntSushi/toml/cmd/tomlv@latest"
]
