lang = "Java SDKMAN"
deps = [ "java" ]
pre = ". ~/.sdkman/bin/sdkman-init.sh && sdk selfupdate"
post = ". ~/.sdkman/bin/sdkman-init.sh && sdk update"
command = ". ~/.sdkman/bin/sdkman-init.sh && sdk install"

[packages]
tools = [ "gradle", "bld" ]
frameworks = [ "springboot", "micronaut", "quarkus" ]
