topic = "Java SDKMAN"
deps = [ "java" ]
upgrade = ". ~/.sdkman/bin/sdkman-init.sh && sdk selfupdate"
post = ". ~/.sdkman/bin/sdkman-init.sh && sdk update"
install = ". ~/.sdkman/bin/sdkman-init.sh && sdk install"

[packages]
tools = [ "maven", "gradle", "bld", "leiningen" ]
frameworks = [ "springboot", "quarkus", "micronaut" ]
langs = [ "kotlin", "groovy" ]
