topic = "PHP Phive"
deps = [ "php", "phive" ]
upgrade = "phive selfupdate"
post = [ "phive update", "phive purge" ]
install = "phive install --target ~/.local/bin"

[packages]
tools = [
  "phpunit",
  "psalm",
  "phing",
  "php-cs-fixer",
  "phpcbf",
  "phpcs",
  "phpstan",
  "phpDocumentor",
  "humbug/box"
]
