topic = "PHP Composer"
deps = [ "php", "composer" ]
upgrade = "composer self-update"
post = "composer global update"
install = "composer global require --no-interaction --with-all-dependencies"

[packages]
frameworks = [ "laravel/installer" ]
tools = [
  "guzzlehttp/guzzle",
  "techlivezheng/phpctags",
  "clue/phar-composer",
  "zircote/swagger-php"
]
apps = [ "psy/psysh" ]

