lang = "php_composer"
deps = [ "php", "composer" ]
pre = "composer self-update"
post = "composer global update"
command = "composer global require --no-interaction --with-all-dependencies"

[packages]
frameworks = [ "laravel/installer" ]
tools = [
  "guzzlehttp/guzzle",
  "techlivezheng/phpctags",
  "clue/phar-composer",
  "zircote/swagger-php"
]
apps = [ "psy/psysh" ]

