topic = "Python Pip"
deps = [ "python3" ]
install = "python3 -m pip install --upgrade --user --break-system-packages"

[packages]
base = [
     "pip",
     "setuptools",
     "wheel"
]
tools = [
  "rope",
  "pipenv",
  "pyflakes",
  "mccabe",
  "pycodestyle",
  "pydocstyle",
  "pytest",
  "autopep8",
  "flake8",
  "pylint",
  "yapf",
  "isort",
  "nose",
  "pyperclip",
  "pytaglib",
  "twine",

  "gdtoolkit",
  "grip",
  "gitpython"
  # "semgrep"
]
apps = [
  "https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz",
  "black",
]
langs = [
      "python-lsp-server[all]",
]
libs = [ "beautifulsoup4", "interval" ]
ops = [ "cryptography" ]
frameworks = [ "fastapi" ]
