lang = "Python Pip"
deps = [ "python3" ]
command = "python3 -m pip install --upgrade --user --break-system-packages"

[packages]
tools = [
  "black",
  "rope",
  "pipenv",
  "pyflakes",
  "mccabe",
  "pycodestyle",
  "pydocstyle",
  "pytest",
  "autopep8",
  "flake8",
  "pylint",
  "yapf",
  "isort",
  "nose",
  "pyperclip",
  "pytaglib",
  "twine",
  "python-lsp-server[all]",
  "gdtoolkit",
  "grip",
  "gitpython"
]
libs = [ "beautifulsoup4", "interval", "yt-dlp" ]
ops = [ "cryptography" ]
