lang = "ruby"
deps = [ "ruby", "gem" ]
pre = "gem update --system"
post = "gem update"
command = "gem install"

[packages]
essentials = [
  "bundler",
  "rake"
]
tools = [
  "rails",
  "reek",
  "rufo",
  "rubocop",
  "pry"
]
libs = [
  "taglib-ruby"
]
