lang = "rust_cargo"
deps = [ "cargo" ]
command = "cargo install"

[packages]
tools = [
  "rust-script",
  "toml-cli",
  "taplo",
  "cargo-watch"
]
apps = [
  "starship",
  "bottom"
]
misc = [
  "--features 'pcre2' ripgrep",
  "fd-find",
  "exa",
  "bat",
  "procs",
  "sd",
  "du-dust",
  "tokei"
]
